function pop=replace_individuals(pop,idx,MLC_parameters,MLC_table,pop_old)
    % REPLACE_INDIVIDUALS replace given indiviuals by new individuals.
    % This function replaces individuals to be removed with new individuals but does not
    % evaluate them.
    % The new individuals are generated by evolving the last population (pop_old)
    % This function can be simplified.
    %
    % Guy Y. Cornejo Maceda, 01/24/2020
    %
    % See also pretesting, find_bad_individuals, remove_bad_individuals.

    % Copyright: 2020 Guy Cornejo Maceda (gy.cornejo.maceda@gmail.com)
    % CC-BY-SA

%% Parameters
MLC_parameters.ExploreIC=0;

%% Initialization
    % Number of new individuals
NNewIndiv = length(idx);

%% Replacement
% If first generation
if pop.generation == 1
    % Create population
    new_subpop = MLCpop(pop.generation,NNewIndiv);
    new_subpop.create_pop(MLC_parameters,MLC_table);
    % Replacement
    pop.individuals(idx) = new_subpop.individuals;
    pop.chromosome_lengths(idx,:) = new_subpop.chromosome_lengths;

% If the new individuals are evolved from a generation
else
    new_subpop = pop_old.evolve_pop(MLC_parameters,MLC_table,NNewIndiv);
    
    %% Replacement
    pop.individuals(idx) = new_subpop.individuals;
    pop.chromosome_lengths(idx,:) = new_subpop.chromosome_lengths;
    pop.parents(idx,:) = new_subpop.parents;
    pop.operation(idx,:) = new_subpop.operation;
end
